#!/usr/bin/sh

# tor (torrent) - takes a .torrent filepath or magnet link uri as the only argument
# downloads torrents to /mnt/usb2

# if no args read from stdin
if [ -z "$1" ]
then
    read url
    rtorrent $url
    exit 0
fi

rtorrent $1
